name: Run Test Suite
on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**.md"
      - ".github/**"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "**.md"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
        laravel: [9.*, 10.*, 11.*, 12.*]
        dependency-version: [prefer-lowest, prefer-stable]
        testbench: ["^7.0", "^8.0", "^9.0", "^10.0"]
        include:
          - laravel: "^12.0"
            testbench: 10.*
          - laravel: "^11.0"
            testbench: 9.*
          - laravel: "^10.0"
            testbench: 8.*
          - laravel: "^9.0"
            testbench: 7.*
        exclude:
          - laravel: "^12.0"
            php: 8.1
          - laravel: "^12.0"
            php: 8.0
          - laravel: "^11.0"
            php: 8.1
          - laravel: "^11.0"
            php: 8.0
          - laravel: "^10.0"
            php: 8.0
          - laravel: "^8.12"
            php: 8.3
          - laravel: "^8.12"
            php: 8.4
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.dependency-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "symfony/console:>=4.3.4" "mockery/mockery:^1.3.2" "nesbot/carbon:>=2.72.6" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest --colors=always
